In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
df = pd.read_csv(r"C:\Users\prati\OneDrive\Desktop\AI-Analytics-Copilot\data\sales_data.csv")

In [3]:
df.head()

,Order_ID,Order_Date,Customer_ID,Product,Region,Payment_Method,Customer_Type,Quantity,Category,Unit_Price,Discount,Gross_Sales,Discount_Amount,Sales,Cost,Profit,Profit_Margin
0,ORD-108925,2024-01-01,CUST-4980,Shoes,South,Cash on Delivery,Returning,4,Fashion,2155,0.0,8620,0.00,8620.00,6838.72,1781.28,20.66
1,ORD-108744,2024-01-01,CUST-1490,T-Shirt,North,Credit Card,VIP,3,Fashion,2247,25.0,6741,1685.25,5055.75,3829.74,1226.01,24.25
2,ORD-105049,2024-01-01,CUST-1659,Smartphone,South,Net Banking,VIP,4,Electronics,36690,25.0,146760,36690.00,110070.00,61815.15,48254.85,43.84
3,ORD-102440,2024-01-01,CUST-1526,Blender,Central,UPI,New,3,Home & Kitchen,6445,15.0,19335,2900.25,16434.75,9528.96,6905.79,42.02
4,ORD-100869,2024-01-01,CUST-2827,Headphones,East,UPI,New,2,Electronics,2896,10.0,5792,579.20,5212.80,4242.69,970.11,18.61

In [4]:
df.shape

(10050, 17)

In [5]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Product', 'Region',
       'Payment_Method', 'Customer_Type', 'Quantity', 'Category', 'Unit_Price',
       'Discount', 'Gross_Sales', 'Discount_Amount', 'Sales', 'Cost', 'Profit',
       'Profit_Margin'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10050 entries, 0 to 10049
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         10050 non-null  str
 1   Order_Date       10050 non-null  str
 2   Customer_ID      10050 non-null  str
 3   Product          10050 non-null  str
 4   Region           10050 non-null  str
 5   Payment_Method   10050 non-null  str
 6   Customer_Type    10000 non-null  str
 7   Quantity         10050 non-null  int64
 8   Category         10050 non-null  str
 9   Unit_Price       10050 non-null  int64
 10  Discount         9948 non-null   float64
 11  Gross_Sales      10050 non-null  int64
 12  Discount_Amount  10050 non-null  float64
 13  Sales            10050 non-null  float64
 14  Cost             10050 non-null  float64
 15  Profit           10050 non-null  float64
 16  Profit_Margin    10050 non-null  float64
dtypes: float64(6), int64(3), str(8)
memory usage: 1.3 MB

In [7]:
df.isnull().sum()

Order_ID             0
Order_Date           0
Customer_ID          0
Product              0
Region               0
Payment_Method       0
Customer_Type       50
Quantity             0
Category             0
Unit_Price           0
Discount           102
Gross_Sales          0
Discount_Amount      0
Sales                0
Cost                 0
Profit               0
Profit_Margin        0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(50)

In [9]:
df[df.duplicated()].head()

,Order_ID,Order_Date,Customer_ID,Product,Region,Payment_Method,Customer_Type,Quantity,Category,Unit_Price,Discount,Gross_Sales,Discount_Amount,Sales,Cost,Profit,Profit_Margin
506,ORD-104521,2024-02-06,CUST-4629,Blender,East,Net Banking,New,3,Home & Kitchen,1978,0.0,5934,0.0,5934.0,3533.57,2400.43,40.45
614,ORD-109920,2024-02-14,CUST-4988,Headphones,South,Debit Card,New,4,Electronics,12101,20.0,48404,9680.8,38723.2,25688.08,13035.12,33.66
782,ORD-105589,2024-02-26,CUST-2772,Tablet,South,Cash on Delivery,VIP,2,Electronics,17414,0.0,34828,0.0,34828.0,20932.59,13895.41,39.90
1103,ORD-109317,2024-03-19,CUST-2869,Keyboard,North,Debit Card,VIP,2,Electronics,5736,0.0,11472,0.0,11472.0,9560.80,1911.20,16.66
1260,ORD-101760,2024-03-30,CUST-4452,Mouse,South,Credit Card,VIP,4,Electronics,1546,5.0,6184,309.2,5874.8,3359.94,2514.86,42.81

In [10]:
df = df.drop_duplicates()

In [11]:
df.shape

(10000, 17)

In [12]:
df[df["Discount"].isnull()].head()

,Order_ID,Order_Date,Customer_ID,Product,Region,Payment_Method,Customer_Type,Quantity,Category,Unit_Price,Discount,Gross_Sales,Discount_Amount,Sales,Cost,Profit,Profit_Margin
22,ORD-107668,2024-01-03,CUST-3806,Coffee Maker,West,UPI,Returning,2,Home & Kitchen,14961,NaN,29922,2992.2,26929.8,20705.04,6224.76,23.11
60,ORD-107502,2024-01-06,CUST-4780,Backpack,Central,Credit Card,VIP,3,Accessories,3997,NaN,11991,2398.2,9592.8,5312.47,4280.33,44.62
64,ORD-101592,2024-01-07,CUST-2934,T-Shirt,South,Cash on Delivery,Returning,1,Fashion,1820,NaN,1820,273.0,1547.0,1150.60,396.40,25.62
83,ORD-101687,2024-01-08,CUST-3161,Keyboard,West,Debit Card,VIP,5,Electronics,908,NaN,4540,908.0,3632.0,2751.67,880.33,24.24
115,ORD-102684,2024-01-10,CUST-2646,Jeans,Central,Net Banking,New,2,Fashion,2350,NaN,4700,470.0,4230.0,2375.70,1854.30,43.84

In [13]:
df[df["Customer_Type"].isnull()].head()

,Order_ID,Order_Date,Customer_ID,Product,Region,Payment_Method,Customer_Type,Quantity,Category,Unit_Price,Discount,Gross_Sales,Discount_Amount,Sales,Cost,Profit,Profit_Margin
102,ORD-100952,2024-01-09,CUST-1357,Laptop,Central,Debit Card,NaN,4,Electronics,78990,0.0,315960,0.0,315960.0,230346.76,85613.24,27.10
218,ORD-105639,2024-01-16,CUST-2920,Coffee Maker,South,Credit Card,NaN,3,Home & Kitchen,11266,10.0,33798,3379.8,30418.2,24895.08,5523.12,18.16
266,ORD-107079,2024-01-20,CUST-2150,Coffee Maker,West,Debit Card,NaN,4,Home & Kitchen,11653,5.0,46612,2330.6,44281.4,26310.00,17971.40,40.58
338,ORD-105441,2024-01-25,CUST-4563,Smartwatch,East,Credit Card,NaN,4,Electronics,6719,15.0,26876,4031.4,22844.6,16956.92,5887.68,25.77
453,ORD-109748,2024-02-02,CUST-4339,Smartwatch,North,Net Banking,NaN,1,Electronics,2073,20.0,2073,414.6,1658.4,1020.24,638.16,38.48

In [14]:
df.dropna()

,Order_ID,Order_Date,Customer_ID,Product,Region,Payment_Method,Customer_Type,Quantity,Category,Unit_Price,Discount,Gross_Sales,Discount_Amount,Sales,Cost,Profit,Profit_Margin
0,ORD-108925,2024-01-01,CUST-4980,Shoes,South,Cash on Delivery,Returning,4,Fashion,2155,0.0,8620,0.00,8620.00,6838.72,1781.28,20.66
1,ORD-108744,2024-01-01,CUST-1490,T-Shirt,North,Credit Card,VIP,3,Fashion,2247,25.0,6741,1685.25,5055.75,3829.74,1226.01,24.25
2,ORD-105049,2024-01-01,CUST-1659,Smartphone,South,Net Banking,VIP,4,Electronics,36690,25.0,146760,36690.00,110070.00,61815.15,48254.85,43.84
3,ORD-102440,2024-01-01,CUST-1526,Blender,Central,UPI,New,3,Home & Kitchen,6445,15.0,19335,2900.25,16434.75,9528.96,6905.79,42.02
4,ORD-100869,2024-01-01,CUST-2827,Headphones,East,UPI,New,2,Electronics,2896,10.0,5792,579.20,5212.80,4242.69,970.11,18.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10045,ORD-104701,2025-12-31,CUST-2054,Headphones,North,Credit Card,Returning,4,Electronics,10884,5.0,43536,2176.80,41359.20,24612.02,16747.18,40.49
10046,ORD-105588,2025-12-31,CUST-4063,Mouse,West,UPI,New,1,Electronics,563,15.0,563,84.45,478.55,406.16,72.39,15.13
10047,ORD-100494,2025-12-31,CUST-4394,Jacket,North,Net Banking,Returning,3,Fashion,2586,5.0,7758,387.90,7370.10,5457.08,1913.02,25.96
10048,ORD-106212,2025-12-31,CUST-1068,Smartphone,South,Cash on Delivery,Returning,3,Electronics,76094,15.0,228282,34242.30,194039.70,147542.88,46496.82,23.96
10049,ORD-102689,2025-12-31,CUST-4155,Shoes,North,Cash on Delivery,Returning,4,Fashion,6738,5.0,26952,1347.60,25604.40,19965.42,5638.98,22.02

In [15]:
df[df["Discount"].isnull()].head()

,Order_ID,Order_Date,Customer_ID,Product,Region,Payment_Method,Customer_Type,Quantity,Category,Unit_Price,Discount,Gross_Sales,Discount_Amount,Sales,Cost,Profit,Profit_Margin
22,ORD-107668,2024-01-03,CUST-3806,Coffee Maker,West,UPI,Returning,2,Home & Kitchen,14961,NaN,29922,2992.2,26929.8,20705.04,6224.76,23.11
60,ORD-107502,2024-01-06,CUST-4780,Backpack,Central,Credit Card,VIP,3,Accessories,3997,NaN,11991,2398.2,9592.8,5312.47,4280.33,44.62
64,ORD-101592,2024-01-07,CUST-2934,T-Shirt,South,Cash on Delivery,Returning,1,Fashion,1820,NaN,1820,273.0,1547.0,1150.60,396.40,25.62
83,ORD-101687,2024-01-08,CUST-3161,Keyboard,West,Debit Card,VIP,5,Electronics,908,NaN,4540,908.0,3632.0,2751.67,880.33,24.24
115,ORD-102684,2024-01-10,CUST-2646,Jeans,Central,Net Banking,New,2,Fashion,2350,NaN,4700,470.0,4230.0,2375.70,1854.30,43.84

In [16]:
df[df["Customer_Type"].isnull()].head()

,Order_ID,Order_Date,Customer_ID,Product,Region,Payment_Method,Customer_Type,Quantity,Category,Unit_Price,Discount,Gross_Sales,Discount_Amount,Sales,Cost,Profit,Profit_Margin
102,ORD-100952,2024-01-09,CUST-1357,Laptop,Central,Debit Card,NaN,4,Electronics,78990,0.0,315960,0.0,315960.0,230346.76,85613.24,27.10
218,ORD-105639,2024-01-16,CUST-2920,Coffee Maker,South,Credit Card,NaN,3,Home & Kitchen,11266,10.0,33798,3379.8,30418.2,24895.08,5523.12,18.16
266,ORD-107079,2024-01-20,CUST-2150,Coffee Maker,West,Debit Card,NaN,4,Home & Kitchen,11653,5.0,46612,2330.6,44281.4,26310.00,17971.40,40.58
338,ORD-105441,2024-01-25,CUST-4563,Smartwatch,East,Credit Card,NaN,4,Electronics,6719,15.0,26876,4031.4,22844.6,16956.92,5887.68,25.77
453,ORD-109748,2024-02-02,CUST-4339,Smartwatch,North,Net Banking,NaN,1,Electronics,2073,20.0,2073,414.6,1658.4,1020.24,638.16,38.48

In [17]:
discount_median = df["Discount"].median()

df["Discount"] = df["Discount"].fillna(discount_median)

print("Missing Discount values filled.")
print("Median Discount:", discount_median)

Missing Discount values filled.
Median Discount: 10.0

In [18]:
discount_median = df["Discount"].median()

df["Discount"] = df["Discount"].fillna(discount_median)

print("Missing Discount values filled.")
print("Median Discount:", discount_median)

Missing Discount values filled.
Median Discount: 10.0

In [19]:
customer_type_mode = df["Customer_Type"].mode()[0]

df["Customer_Type"] = df["Customer_Type"].fillna(customer_type_mode)

print("Missing Customer_Type values filled.")
print("Mode Customer Type:", customer_type_mode)

Missing Customer_Type values filled.
Mode Customer Type: New

In [20]:
customer_type_mode = df["Customer_Type"].mode()[0]

df["Customer_Type"] = df["Customer_Type"].fillna(customer_type_mode)

print("Missing Customer_Type values filled.")
print("Mode Customer Type:", customer_type_mode)

Missing Customer_Type values filled.
Mode Customer Type: New

In [21]:
print("Missing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

Missing Values:
Order_ID           0
Order_Date         0
Customer_ID        0
Product            0
Region             0
Payment_Method     0
Customer_Type      0
Quantity           0
Category           0
Unit_Price         0
Discount           0
Gross_Sales        0
Discount_Amount    0
Sales              0
Cost               0
Profit             0
Profit_Margin      0
dtype: int64

Duplicate Rows:
0